#!/bin/sh
#
# Hook script to verify what is about to be committed.
# Called by "git commit" with no arguments. The hook
# should exit with non-zero status after issuing an
# appropriate message if RAML files on commit don't
# pass raml-validator .

echo '********************************************************'
echo '    Install node ...'
echo '********************************************************'
if ! type node > /dev/null; then
  curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  apt-get install -y nodejs
else
  echo "node is installed, skipping..."
fi

echo '********************************************************'
echo '    Install  raml-js-validator ...'
echo '********************************************************'

if npm list -g raml-js-validator
then
  echo "raml-js-validator is installed, skipping..."
else
  npm install -g raml-js-validator
fi

echo '********************************************************'
echo '    Check RAML files ...'
echo '********************************************************'

AREVALID=true
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
NC='\033[0m'

for file in `git diff --cached --name-only --diff-filter=ACM`
do

if [ "${file##*.}" = "raml" ]
  then
    echo "${BROWN}--------------------------------"
    echo " Checking file: ${file}"
    echo "--------------------------------${NC}"
    if raml-validate $file; then continue;
    else AREVALID=false; fi
  fi
done

if $AREVALID
then
  echo "${GREEN}Checked files on current commit: OK"
  exit 0
else
  echo "${RED}Checked files on current commit: KO"
  exit 1
fi
